# Generated by Django 4.1.4 on 2022-12-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagondefect',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
